"""NAIF PDS4 Bundler Command Line Interface (CLI)
"""
from argparse import ArgumentParser, RawDescriptionHelpFormatter

from .. import __version__
from ..utils.types.datatypes import PipelineArgs


# TODO: - Remove from "config" argument nargs: only one configuration file
#         can be provided.
#       - Add actions to those arguments that are supposed to be files. The
#         output of those actions should be a PathLike object.
#       - Convert those arguments that are "lists" (faucet, diff) of options
#         to "choices" type.
def parse_arguments() -> PipelineArgs:
    """Parse command-line arguments and return a validated pipeline argument
    container.

    Builds an :class:`~argparse.ArgumentParser` with all NPB CLI arguments,
    parses ``sys.argv``, and packages the result into a frozen
    :class:`~.datatypes.PipelineArgs` instance with ``debug`` set to
    ``False`` (debugging is disabled when running from the command line).

    :returns: Validated and normalized pipeline arguments.
    """
    # Build the argument parser.
    parser = ArgumentParser(
        formatter_class=RawDescriptionHelpFormatter,
        description=f"\nnaif-pds4-bundler-{__version__}, NAIF PDS4 SPICE archive generation pipeline\n"
                    "  naif-pds4-bundler is a command-line utility program that generates PDS4"
                    "  bundles for SPICE kernel archives."
    )
    parser.add_argument(
        "config",
        metavar="CONFIG",
        type=str,
        nargs="+",
        help="XML Configuration file",
    )
    parser.add_argument(
        "-p",
        "--plan",
        action="store",
        type=str,
        help="Release plan file listing the kernels and/or "
        "ORBNUM files to be archived. If this argument is not "
        "provided, all the kernels found in the "
        "kernels directory specified in the "
        "configuration file in addition to new "
        "meta-kernels will be included in the "
        "increment. If the ``-x --xml`` argument is used "
        "this argument can be the name of a kernel or the path "
        "to a release plan file (ORBNUM files will be ignored.)",
    )
    parser.add_argument(
        "-f",
        "--faucet",
        default="",
        action="store",
        type=str,
        help="Optional indication for end point of the "
        "pipeline. Allowed values are: ``clear``, "
        "``plan``, ``list``, ``checks``, ``staging``, ``bundle``, and ``labels``.",
    )
    parser.add_argument(
        "-l",
        "--log",
        help="Write log in file. The file is written in the"
        "``working_directory`` specified in the configuration file.",
        action="store_true",
    )
    parser.add_argument(
        "-s",
        "--silent",
        help="Log will not be prompted on the terminal during execution.",
        action="store_true",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        help="Full log will be prompted on the terminal "
        "during execution. If the argument is provided "
        "the ``-s, --silent`` argument is omitted.",
        action="store_true",
    )
    parser.add_argument(
        "-d",
        "--diff",
        default="",
        action="store",
        type=str,
        help="Optional generation of diff reports for "
        "products. Allowed values are: ``files``, ``log``, and ``all``. "
        "Files are written in the ``working_directory`` specified in the "
        "configuration file.",
    )
    parser.add_argument(
        "-c",
        "--clear",
        default="",
        action="store",
        type=str,
        help="Clears the files listed in the input file "
        "from the staging and bundle directories and the "
        "kernel list from the working directory. The input "
        "file should be as generated by a prior "
        "execution with a ``*.file_list`` extension. "
        "If this argument is provided "
        "it overwrites the faucet argument to ``clear`` "
        "and therefore the pipeline is not executed. "
        "If you provide the adequate ``-f, --faucet`` argument, the "
        "pipeline will be executed until indicated.",
    )
    parser.add_argument(
        "-k",
        "--kerlist",
        action="store",
        type=str,
        help="Release plan file listing the kernels to "
        "be archived along with some parameters "
        "required for the run. If this argument is "
        "provided the release plan is not generated.",
    )
    parser.add_argument(
        "-m",
        "--checksum",
        help="Obtain MD5 Sums for products defined in the Checksum Registry "
        "file generated by a previous run. These files are stored in "
        "in the ``working_directory`` specified in the configuration and "
        "have a ``*.checksum`` extension. If no Checksum Registry files "
        "are available product labels from the staging directory will "
        "be used. This argument is useful if large files have already "
        "been processed by a previous run.",
        action="store_true",
    )

    # Parse the command line arguments into the pipeline arguments data type.
    # Set debug mode to False (no debugging when executed from the command line.
    args = parser.parse_args()
    args.config = args.config[0]

    return PipelineArgs(**vars(args), debug=False)
