repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: REQUIREMENTS\.md$
    -   id: end-of-file-fixer
        exclude: REQUIREMENTS\.md$
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--extend-ignore=W503,E203']

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: python -m unittest discover -s tests/naif_pds4_bundler
        language: system
        stages: [push]
        pass_filenames: false
