repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: python3 -m unittest discover -s tests/naif_pds4_bundler
        language: system
        stages: [pre-push]
        pass_filenames: false
