"""Implementation of the NAIF PDS4 Bundler pipeline.
"""
import logging
from os.path import isdir
from pathlib import Path

from .runtime import clear_run, finish_execution
from .. import __version__
from ..classes.bundle import Bundle
from ..classes.collection import DocumentCollection
from ..classes.collection import MiscellaneousCollection
from ..classes.collection import SpiceKernelsCollection
from ..classes.list import KernelList
from ..classes.log import Log
from ..classes.plan import ReleasePlan
from ..classes.product import ChecksumProduct, ReadmeProduct
from ..classes.product import InventoryProduct
from ..classes.product import MetaKernelProduct
from ..classes.product import OrbnumFileProduct
from ..classes.product import SpicedsProduct
from ..classes.product import SpiceKernelProduct
from ..classes.setup import Setup
from ..utils.types.datatypes import PipelineArgs


def run_pipeline(args: PipelineArgs) -> None:
    """NAIF PDS4 Bundler pipeline for the archive generation.

    :param args: Command line arguments, with the following attributes:

        config: XML Configuration file
        plan: Release plan file listing the kernels to be archived.
              If this argument is not provided, all the kernels found in
              the kernels directory specified in the configuration file
              in addition to new meta-kernels will be included in the
              increment
        plan: str
        faucet: Optional indication for end point of the pipeline.
                Allowed values are: `clear``, ``plan``, ``list``,
                ``checks``, ``staging``, ``bundle``, and ``labels``.
        faucet: str
        log: Write log in file. The file is written in the
             ``working_directory`` specified in the configuration file.
        log: bool
        silent: Log will not be prompted on the terminal during execution
        silent: bool
        verbose: Full log will be prompted on the terminal  during
                 execution. If argument is set to True, silent argument
                 is omitted
        verbose: bool
        diff: Optional generation of diff reports for products. Allowed
              values are: ``files``, ``log``, and ``all``.
        diff: str
        debug: Indicate whether if the pipeline is running in debug mode.
               If so the format of the logging is different and the files
               generated in a failed run are not cleaned up.
        debug: bool
        clear: Indicates if the pipeline will run only to clear previous
               run and specifies the file that indicates the files to be cleared.
        clear: str
        kerlist: Release list file listing the kernels to be archived along
              with their description.
        kerlist: str
        checksum: Obtain MD5 Sums for products defined in the Checksum Registry
                  file generated by a previous run. These files are stored
                  in the ``working_directory`` specified in the configuration
                  and have a ``*.checksum`` extension.
                  If no Checksum Registry files are available product labels from
                  the staging directory will be used. This argument is useful
                  if large files have already been processed by a previous run.
        checksum: bool
    """
    #
    # The pipeline execution per se starts now.
    #
    # * Generate the Setup object
    #     * This object will be used by all the other objects
    #     * Parse JSON into an object with attributes corresponding
    #       to dict keys.
    #
    setup = Setup(args, __version__)

    #
    # * Start the Log object
    #    * The log will always be displayed on screen unless the silent
    #      option is chosen.
    #    * The log file will be written in the working directory
    #
    log = Log(setup, args)

    #
    # Indicate the Log object to start recording the output.
    #
    log.start()

    #
    # Add the log to the setup object with the sole purpose for the log
    # to be accessible via setup to be able to write the product list file
    # for an interrupted run.
    #
    setup.log = log

    #
    # With the log started we check the current configuration
    #
    setup.check_configuration()

    #
    # * Check the existence of a previous archive version.
    #
    setup.set_release()

    #
    # * If the pipeline is running to clean up a previous run, remove all the
    #   files in the bundle and staging area indicated by the file list and
    #   clean up the kernel list and log from the previous run.
    #
    if args.clear:
        clear_run(setup)

    #
    #    * The pipeline can be stopped after cleaning up the previous run
    #      by setting ``-f, --faucet`` to ``clear``.
    #
    if setup.faucet == "clear":
        finish_execution(setup, log)
        return

    #
    # * Generate the Release Plan object.
    #
    release_plan = ReleasePlan(setup)

    #
    #    * If a plan file is provided it is processed otherwise a plan is
    #      generated from the kernels' directory.
    #
    #    * If NPB is run in label generation mode and no input products are
    #      found, stop the execution.
    #
    if not args.kerlist:
        if not args.plan or (".plan" not in args.plan):

            # Stop the execution if we cannot write a release plan when we are
            # running on "labels" mode.
            if not release_plan.write_plan() and (args.faucet == "labels"):
                return
        else:
            release_plan.read_plan(Path(args.plan))

    #
    #    * The pipeline can be stopped after generating or reading the release
    #      plan by setting ``-f, --faucet`` to ``plan``.
    #
    if setup.faucet == "plan":
        finish_execution(setup, log)
        return

    #
    # * Generate the Kernel List object.
    #
    #   If a release plan was either generated or loaded during the previous
    #   step, load the obtained kernel_list into the KernelList object.
    #
    # TODO: Add kernel_list argument to the KernelList constructor.
    k_list = KernelList(setup)
    k_list.kernel_list = release_plan.kernel_list

    if not args.kerlist:
        k_list.write_list()
    else:
        k_list.read_list(args.kerlist)

    #
    #    * The pipeline can be stopped after generating or reading the kernel
    #      list plan by setting ``-f, --faucet`` to ``list``.
    #
    if setup.faucet == "list":
        finish_execution(setup, log)
        return

    #
    #    * Check the products present in the list (SPICE kernels and ORBNUM
    #      files)
    k_list.check_products()

    #
    #    * The pipeline can be stopped after checking the kernel
    #      list by setting ``-f, --faucet`` to ``checks``.
    #
    if setup.faucet == "checks":
        finish_execution(setup, log)
        return

    #
    # * Generate the PDS4 Bundle structure.
    #
    bundle = Bundle(setup)

    #
    # * Load LSK, FK and SCLK kernels for time conversions and coverage
    #   computations.
    #
    setup.load_kernels()

    #
    # * Initialize the SPICE Kernels Collection.
    #
    spice_kernels_collection = SpiceKernelsCollection(setup, bundle, k_list)

    #
    # * Initialize the Miscellaneous Collection.
    #
    miscellaneous_collection = MiscellaneousCollection(setup, bundle, k_list)

    #
    # * Generate the labels for each SPICE kernel or ORBNUM product and
    #   populate the SPICE kernels collection or the Miscellaneous collection
    #   accordingly.
    #
    for kernel in k_list.kernel_list:
        #
        # * Each label is validated after generation.
        #
        if (".nrb" in kernel.lower()) or (".orb" in kernel.lower()):
            #
            # The OrbnumFileProduct has to be provided the kernels collection
            # because it might require to update the kernel list if the
            # orbnum file name is updated.
            #
            miscellaneous_collection.add(
                OrbnumFileProduct(
                    setup, kernel, miscellaneous_collection, spice_kernels_collection
                )
            )
        elif ".tm" not in kernel.lower():
            spice_kernels_collection.add(
                SpiceKernelProduct(setup, kernel, spice_kernels_collection)
            )

    #
    # * Generate the Meta-kernel(s).
    #
    meta_kernels = spice_kernels_collection.determine_meta_kernels()
    if meta_kernels:
        for mk in sorted(meta_kernels):
            meta_kernel = MetaKernelProduct(
                setup, mk, spice_kernels_collection, user_input=meta_kernels[mk]
            )
            if setup.pds_version == "4":
                spice_kernels_collection.add(meta_kernel)
            else:
                miscellaneous_collection.add(meta_kernel)

    #
    # * Faucet for labeling mode.
    #
    if args.faucet == "labels":

        #
        # * Add the SPICE Kernels Collection to the Bundle.
        #
        bundle.add(spice_kernels_collection)

        #
        # * List the files present in the staging area.
        #
        bundle.files_in_staging()

        #
        # * Copy files to the bundle area.
        #
        bundle.copy_to_bundle()

        finish_execution(setup, log)
        return

    #
    # * Determine the SPICE kernels Collection increment times and VID.
    #
    if setup.pds_version == "4":
        spice_kernels_collection.set_increment_times()
        spice_kernels_collection.set_collection_vid()

    #
    # * Validate the SPICE Kernels collection:
    #    * Note the validation of products is performed after writing the
    #      product itself and, therefore, it is not explicitly executed
    #      from at object initialization.
    #    * Check if there is an XML label for each file under spice_kernels.
    #
    spice_kernels_collection.validate()

    #
    # *  Generate the SPICE Kernels Collection Inventory product (if the
    #    collection has been updated.)
    #
    if spice_kernels_collection.updated:
        if setup.pds_version == "4":
            spice_kernels_collection.set_collection_vid()
        spice_kernels_collection_inventory = InventoryProduct(
            setup, spice_kernels_collection
        )
        spice_kernels_collection.add(spice_kernels_collection_inventory)

    if setup.pds_version == "4":
        #
        # * Generate the Document Collection.
        #
        document_collection = DocumentCollection(setup, bundle)
        document_collection.set_collection_vid()

        #
        # * Generate of SPICEDS document.
        #
        spiceds = SpicedsProduct(setup, document_collection)

        #
        # * If the SPICEDS document is generated, generate the
        #   Documents Collection Inventory.
        #
        if spiceds.generated:
            document_collection.add(spiceds)

            document_collection.set_collection_vid()
            document_collection_inventory = InventoryProduct(setup, document_collection)
            document_collection.add(document_collection_inventory)

        #
        # * Add the SPICE Kernels Collection to the Bundle.
        #   Note that the Collections are provided to the Bundle object
        #   in a given order.
        #
        bundle.add(spice_kernels_collection)

        #
        # * Generate the Miscellaneous collection. The Checksum product
        #   is initialized in such a way that its name can be obtained.
        #
        # * The first thing that is checked is whether if the current
        #   Bundle has checksums, if not, all the checksums are generated,
        #   including the corresponding Miscellaneous Collection Inventories
        #   and labels.
        #

        # Report the Collection generation step.
        line = f"Step {setup.step} - Generation of {miscellaneous_collection.kind} collection"
        logging.info("")
        logging.info(line)
        logging.info("-" * len(line))
        logging.info("")
        setup.step += 1
        if not setup.args.silent and not setup.args.verbose:
            print("-- " + line.split(" - ")[-1] + ".")

        if setup.increment:
            checksum_dir = (
                setup.bundle_directory
                + f"/{setup.mission_acronym}_spice/miscellaneous/checksum"
            )
            if not isdir(checksum_dir):
                for release in bundle.history.items():
                    release_checksum = ChecksumProduct(
                        setup, miscellaneous_collection, add_previous_checksum=False
                    )
                    release_checksum.generate(history=release)

                    #
                    # Initialize a miscellaneous collection for this previous
                    # release.
                    #
                    release_miscellaneous_collection = MiscellaneousCollection(
                        setup, bundle, k_list
                    )

                    #
                    # Add the checksum at the release miscellaneous collection
                    # to generate the adequate inventory file and add it to
                    # the current miscellaneous collection for it to be
                    # present at the checksum.
                    #
                    release_miscellaneous_collection.add(release_checksum)

                    miscellaneous_collection.add(release_checksum)

                    release_miscellaneous_collection.set_collection_vid()
                    release_miscellaneous_collection_inventory = InventoryProduct(
                        setup, release_miscellaneous_collection
                    )

                    release_miscellaneous_collection.add(
                        release_miscellaneous_collection_inventory
                    )
                    miscellaneous_collection.add(
                        release_miscellaneous_collection_inventory
                    )

                    #
                    # Add release miscellaneous collection.
                    #
                    bundle.add(release_miscellaneous_collection)

            #
            # * Set the Miscellaneous collection VID.
            #
            miscellaneous_collection.set_collection_vid()

        #
        # * Add the Miscellaneous and Document Collections to the Bundle object.
        #
        bundle.add(miscellaneous_collection)
        bundle.add(document_collection)

        #
        # * Generate Miscellaneous Collection and initialize the Checksum
        #   product for the current release.
        #    * The miscellaneous collection is the one to be guaranteed to be
        #      updated.
        #
        checksum = ChecksumProduct(setup, miscellaneous_collection)

        #
        # Before adding the checksum to the current collection
        # we need to specify that is not a new product.
        #
        for product in miscellaneous_collection.product:
            if type(product) == ChecksumProduct:
                product.new_product = False

        miscellaneous_collection.add(checksum)
        miscellaneous_collection.set_collection_vid()

        checksum.set_coverage()
        miscellaneous_collection_inventory = InventoryProduct(
            setup, miscellaneous_collection
        )
        miscellaneous_collection.add(miscellaneous_collection_inventory)

        #
        # * Generate the Bundle label and if necessary the readme file.
        #
        bundle.readme = ReadmeProduct(setup, bundle)

        #
        # * Generate the Checksum product a posteriori in such a way
        #   that the miscellaneous collection inventory includes the
        #   checksum and the checksum includes the md5 hash of the
        #   Miscellaneous Collection Inventory.
        #
        checksum.generate()
        miscellaneous_collection.add(checksum)

    elif setup.pds_version == "3":

        document_collection = DocumentCollection(setup, bundle)
        document_collection.get_pds3_documents()

        bundle.add(spice_kernels_collection)
        bundle.add(document_collection)
        bundle.add(miscellaneous_collection)

        checksum = ChecksumProduct(
            setup, miscellaneous_collection, add_previous_checksum=False
        )
        checksum.generate()
        miscellaneous_collection.add(checksum)

    #
    # * List the files present in the staging area.
    #
    bundle.files_in_staging()

    #
    # * The pipeline can be stopped after generating the products and before
    #   moving them to the ``bundle_directory`` by setting ``-f, --faucet``
    #   to ``staging``.
    #
    if setup.faucet == "staging":
        finish_execution(setup, log)
        return

    #
    # Generate index files, this includes generating the complete
    # kernel list.
    #
    # OnlyFor PDS3
    # list.write_complete_list()
    # spice_kernels_collection_inventory.write_index()

    #
    # * Copy files to the bundle area.
    #
    bundle.copy_to_bundle()

    #
    # * The pipeline can be stopped after generating the moving the products
    #   ``bundle_directory`` by setting ``-f, --faucet``. Ch
    #   to ``bundle``.
    #
    if setup.faucet == "bundle":
        finish_execution(setup, log)
        return

    #
    # * Validate the Bundle by checking Checksum files against the updated
    #   Bundle history and checking the bundle times.
    #
    if setup.pds_version == "4":
        bundle.validate()

    #
    # * Validate Meta-kernel(s).
    #   This is the last step since it unloads all kernels.
    #
    for kernel in spice_kernels_collection.product:
        if type(kernel) == MetaKernelProduct:
            kernel.validate()

    finish_execution(setup, log)
