from __future__ import annotations
import logging
import os
from pathlib import Path
from typing import NoReturn, Optional, TYPE_CHECKING

import spiceypy

if TYPE_CHECKING:
    from ..classes.setup import Setup
    from ..classes.log import Log


def clear_run(setup: Setup) -> None:
    """Clears the files generated by a previous run.

    Clears the files generated by a previous run when specified with the
    clear argument providing the kernel list of the previous run.

    Please note that newly created directories will not be erased.

    :param setup: NPB configuration.
    """
    if os.path.isfile(setup.args.clear):

        # Read the kernel list file provided in the "clear" argument.
        with open(setup.args.clear, "r", encoding='utf-8') as handle:
            lines = handle.readlines()

        # Remove files from the staging area.
        path = Path(setup.staging_directory)
        logging.info(f"-- Removing files from staging area: {path}.")

        for line in lines:
            if ".plan" not in line and ".kernel_list" not in line:
                _unlink_with_warning(path=path / line.strip())

        # Remove files from the final (bundle) area.
        path = Path(setup.bundle_directory, f'{setup.mission_acronym}_spice')
        logging.info(f"-- Removing files from final area: {path}.")

        executed_in_label_mode = not path.exists()
        for line in lines:
            if ".plan" not in line and ".kernel_list" not in line:
                # When NPB has been executed in label mode, the final
                # area does not replicate the bundle directory structure
                # but kernels operations area.
                if executed_in_label_mode:
                    target = Path(setup.bundle_directory,
                                  line.split("spice_kernels")[-1].strip().lstrip('/'))
                else:
                    target = path / line.strip()
                _unlink_with_warning(path=target)

        # Remove generated by-products from the working_directory.
        path = Path(setup.working_directory)
        if setup.args.kerlist:
            byproduct = Path(setup.args.clear).with_suffix(".plan")
            logging.info(f"-- Removing previous run by-product: {byproduct}.")
            _unlink_with_warning(path=path / byproduct.name)

        if setup.args.plan:
            byproduct = Path(setup.args.clear).with_suffix(".kernel_list")
            logging.info(f"-- Removing previous run by-product: {byproduct}.")
            _unlink_with_warning(path=path / byproduct.name)

    else:
        handle_npb_error(
             message='The file provided with the "clear" argument does '
                     'not exist or is not readable. Make sure that the '
                     'file follows the name pattern: '
                     f'{setup.mission_acronym}_{setup.run_type}_NN.file_list,'
                     ' where NN is the release number.',
            setup=None)


def finish_execution(setup: Setup, log_manager: Log) -> None:
    """Coordinator function for the 'stop' sequence."""

    # Business Logic: Cleanup Templates
    for template in setup.template_files:
        if os.path.exists(template):
            os.remove(template)

    log_step(setup, title='Generate run by-product files')

    # Business Logic: Generate Artifacts
    #
    # Write the run-by product file list and checksum record
    setup.write_file_list()
    setup.write_checksum_registry()

    # The validate file is not generated for an NPB clear run.
    if setup.pds_version == "4" and setup.args.faucet != "clear":
        setup.write_validate_config()

    # Clear the kernel pool
    spiceypy.kclear()

    # Logging Finalization
    log_manager.stop()


def handle_npb_error(message: str, setup: Optional[Setup] = None) -> NoReturn:
    """Signal a NPB error and write run artifacts.

    Side effects:
        - Writes file list and checksum registry if setup is provided
        - Removes template files
        - Clears SPICE kernel pool
        - Raises RuntimeError

    :param message: Error message
    :param setup:   Optional Setup object for writing artifacts

    :raises RuntimeError: always, with the provided error message.
    """
    logging.error(f"-- {message}")

    # If files have been generated in the staging area and/or transferred
    # to the final area, generate the file list for the pipeline execution.
    #
    # In addition, generate the checksum registry file
    if setup:
        setup.write_file_list()
        setup.write_checksum_registry()

        # Remove the templates. Make sure they exist before attempting the
        # deletion.
        for template in setup.template_files:
            if os.path.exists(template):
                os.remove(template)

    # Clear the kernel pool.
    spiceypy.kclear()

    raise RuntimeError(message)


def log_step(setup: Setup, title: str) -> None:
    """Logs the current execution step and increments the counter.

    :param setup: NPB configuration.
    :param title: Step title
    """
    message = f"Step {setup.step} - {title}"
    logging.info("")
    logging.info(message)
    logging.info("-" * len(message))
    logging.info("")

    if not setup.args.silent and not setup.args.verbose:
        print(f"-- {title}.")

    setup.step += 1

# ---------------------------------------------------------------------------
# runtime utility functions
# ---------------------------------------------------------------------------
def _unlink_with_warning(path: Path) -> None:
    """Remove a file, logging a warning if it does not exist."""
    try:
        path.unlink(missing_ok=False)
    except FileNotFoundError:
        logging.warning(f"     File {path} not found.")
