"""**NAIF PDS4 Bundler Main Module**.

usage: naif-pds4-bundler [-h] [-p PLAN] [-f FAUCET] [-l] [-s] [-v] [-d DIFF]
                         [-c CLEAR] [-k KERLIST] CONFIG [CONFIG ...]

**naif-pds4-bundler-0.13.1, NAIF PDS4 SPICE archive generation pipeline**

naif-pds4-bundler is a command-line utility program that generates PDS4
bundles for SPICE kernel archives.

positional arguments:
  CONFIG                XML Configuration file

optional arguments:
  -h, --help            show this help message and exit
  -p PLAN, --plan PLAN  Release plan file listing the kernels and/or ORBNUM
                        files to be archived. If this argument is not
                        provided, all the kernels found in the kernels
                        directory specified in the configuration file
                        in addition to new meta-kernels will be included
                        in the increment. If the ``-x --xml`` argument
                        is used this argument can be the name of a
                        kernel or the path to a release plan file
                        (ORBNUM files will be ignored.)
  -f FAUCET, --faucet FAUCET
                        Optional indication for end point of the pipeline.
                        Allowed values are: ``clear``, ``plan``, ``list``,
                        ``checks``, ``staging``, ``bundle``, and ``labels``.
  -l, --log             Write log in file
  -s, --silent          Log will not be prompted on the terminal during
                        execution.
  -v, --verbose         Full log will be prompted on the terminal during
                        execution. If the argument is provided the
                        ``-s, --silent`` argument is omitted.
  -d DIFF, --diff DIFF  Optional generation of diff reports for products.
                        Allowed values are: ``files``, ``log``, and ``all``.
  -c CLEAR, --clear CLEAR
                        Clears the files listed in the input file from the
                        staging and bundle directories and the kernel list
                        from the working directory. The input file should be
                        as generated by a prior execution with a ``*.file_list``
                        extension. If this argument is provided it
                        overwrites the faucet argument to ``clear`` and
                        therefore the pipeline is not executed. If you
                        provide the adequate ``-f, --faucet`` argument, the
                        pipeline will be executed until indicated.
  -k KERLIST, --kerlist KERLIST
                        Release plan file listing the kernels to be archived
                        along with some parameters required for the run.
                        If this argument is provided the release plan is
                        not generated.

"""
import sys

from .cli import cli_npb
from .pipeline import npb


def main() -> int:
    """Main routine for the NAIF PDS4 Bundler.

    This routine gets the command line arguments and runs the archive
    generation pipeline.

    :returns: a code providing the execution result: 0 if the execution was
              successful, 1 if the execution found a know issue with the
              configuration or input data, and 2 if an unexpected error
              occurred.
    """
    try:
        # Run the command line and get the arguments provided by the user.
        # Note: debug mode is not available.
        args = cli_npb.parse_arguments()

        # Pass the structured arguments to the pipeline orchestrator
        npb.run_pipeline(args)

        return 0

        # TODO: Add NBPError as handler for "known issues."
        # except NBPError:
        #     return 1

    # Handle all other unexpected errors (Return code 2).
    #
    # Note: Since we want to make sure that if the pipeline crashes, we can
    #       capture the exception and gracefully exit, we will allow capturing
    #       the broader possible exception.
    except Exception: # pylint: disable=broad-exception-caught
        # TODO: Add proper reporting for unexpected errors once the NBPError
        #       is implemented.
        #     print(f"An unexpected error occurred:\n\n{e}\n\n"
        #            "Please report it via [add url]", file=sys.stderr)
        return 2


if __name__ == "__main__":
    # After running the application, return the result to the OS.
    sys.exit(main())
