"""**NAIF PDS4 Bundler Main Module**.

usage: naif-pds4-bundler [-h] [-p PLAN] [-f FAUCET] [-l] [-s] [-v] [-d DIFF] [-c CLEAR] [-k KERLIST] CONFIG [CONFIG ...]

**naif-pds4-bundler-0.13.1, NAIF PDS4 SPICE archive generation pipeline**

naif-pds4-bundler is a command-line utility program that generates PDS4
bundles for SPICE kernel archives.

positional arguments:
  CONFIG                XML Configuration file

optional arguments:
  -h, --help            show this help message and exit
  -p PLAN, --plan PLAN  Release plan file listing the kernels and/or ORBNUM
                        files to be archived. If this argument is not
                        provided, all the kernels found in the kernels
                        directory specified in the configuration file
                        in addition to new meta-kernels will be included
                        in the increment. If the ``-x --xml`` argument
                        is used this argument can be the name of a
                        kernel or the path to a release plan file
                        (ORBNUM files will be ignored.)
  -f FAUCET, --faucet FAUCET
                        Optional indication for end point of the pipeline.
                        Allowed values are: ``clear``, ``plan``, ``list``,
                        ``checks``, ``staging``, ``bundle``, and ``labels``.
  -l, --log             Write log in file
  -s, --silent          Log will not be prompted on the terminal during
                        execution.
  -v, --verbose         Full log will be prompted on the terminal during
                        execution. If the argument is provided the
                        ``-s, --silent`` argument is omitted.
  -d DIFF, --diff DIFF  Optional generation of diff reports for products.
                        Allowed values are: ``files``, ``log``, and ``all``.
  -c CLEAR, --clear CLEAR
                        Clears the files listed in the input file from the
                        staging and bundle directories and the kernel list
                        from the working directory. The input file should be
                        as generated by a prior execution with a ``*.file_list``
                        extension. If this argument is provided it
                        overwrites the faucet argument to ``clear`` and
                        therefore the pipeline is not executed. If you
                        provide the adequate ``-f, --faucet`` argument, the
                        pipeline will be executed until indicated.
  -k KERLIST, --kerlist KERLIST
                        Release plan file listing the kernels to be archived
                        along with some parameters required for the run.
                        If this argument is provided the release plan is
                        not generated.

"""
from .cli import cli_npb
from .classes.object import Object
from .pipeline import npb


def main(
    config=False,
    plan=False,
    faucet="",
    log=False,
    silent=False,
    verbose=False,
    diff="",
    debug=True,
    clear="",
    kerlist="",
    checksum=False,
):
    """Main routine for the NAIF PDS4 Bundler.

    This routine gets the command line arguments or the parameter
    arguments and runs the archive generation pipeline.

    :param config: XML Configuration file
    :param plan: Release plan file listing the kernels to be archived.
                 If this argument is not provided, all the kernels found in
                 the kernels directory specified in the configuration file
                 in addition to new meta-kernels will be included in the
                 increment
    :type plan: str
    :param faucet: Optional indication for end point of the pipeline.
                   Allowed values are: `clear``, ``plan``, ``list``,
                   ``checks``, ``staging``, ``bundle``, and ``labels``.
    :type faucet: str
    :param log: Write log in file. The file is written in the
                ``working_directory`` specified in the configuration file.
    :type log: bool
    :param silent: Log will not be prompted on the terminal during execution
    :type silent: bool
    :param verbose: Full log will be prompted on the terminal  during
                    execution. If argument is set to True, silent argument
                    is omitted
    :type verbose: bool
    :param diff: Optional generation of diff reports for products. Allowed
                 values are: ``files``, ``log``, and ``all``.
    :type diff: str
    :param debug: Indicate whether if the pipeline is running in debug mode.
                  If so the format of the logging is different and the files
                  generated in a failed run are not cleaned up.
    :type debug: bool
    :param clear: Indicates if the pipeline will run only to clear previous
    run and specifies the file that indicates the files to be cleared.
    :type clear: str
    :param kerlist: Release list file listing the kernels to be archived along
                 with their description.
    :type kerlist: str
    :param checksum: Obtain MD5 Sums for products defined in the Checksum Registry
                     file generated by a previous run. These files are stored
                     in the ``working_directory`` specified in the configuration
                     and have a ``*.checksum`` extension.
                     If no Checksum Registry files are available product labels from
                     the staging directory will be used. This argument is useful
                     if large files have already been processed by a previous run.
    :type checksum: bool
    """
    # Determine whether if the pipeline is being executed directly from
    # the command line of called by another Python function. If this is
    # not the case, then the arguments are taken from the command line.
    if not config and not plan:

        # Run the command line and get the arguments provided by the user.
        # Note: debug mode is not available.
        args = cli_npb.parse_arguments()

    #
    # If NPB is not executed from the command line then an args object is
    # initialised and the argument attributes are obtained from the
    # main function argument list.
    #
    else:
        args = Object()
        args.config = config
        args.plan = plan
        args.faucet = faucet
        args.log = log
        args.silent = silent
        args.verbose = verbose
        args.diff = diff
        args.debug = debug
        args.clear = clear
        args.kerlist = kerlist
        args.checksum = checksum

    # Pass the structured arguments to the pipeline orchestrator
    npb.run_pipeline(args)


if __name__ == "__main__":
    main()
