"""PDS Label Class and Child Classes Implementation."""

import glob
import logging
import os
from pathlib import Path

from ...utils import add_carriage_return, compare_files


class PDSLabel:
    """Class to generate a PDS Label.

    :param setup:   NPB execution Setup object
    :param product: Product to be labeled
    """

    _label_extension: str

    def __init__(self, setup, product) -> None:
        """Constructor."""
        self.name = ''
        self.product = product
        self.setup = setup

        #
        # Fields from setup
        #
        self.root_dir = setup.root_dir
        self.mission_acronym = setup.mission_acronym

        if hasattr(self.setup, "creation_date_time"):
            creation_dt = self.setup.creation_date_time
            self.PRODUCT_CREATION_TIME = creation_dt
            self.PRODUCT_CREATION_DATE = creation_dt.split("T")[0]
            self.PRODUCT_CREATION_YEAR = creation_dt.split("-")[0]
        else:
            self.PRODUCT_CREATION_TIME = product.creation_time
            self.PRODUCT_CREATION_DATE = product.creation_date
            self.PRODUCT_CREATION_YEAR = product.creation_date.split("-")[0]

        self.FILE_SIZE = product.size
        self.FILE_CHECKSUM = product.checksum

        #
        # For labels that need to include all missions, observers and targets
        # of the setup.
        #
        if type(self).__name__ not in ('SpiceKernelPDS4Label', 'MetaKernelPDS4Label', 'OrbnumFilePDS4Label'):
            #
            # Obtain all Missions
            #
            mis = [self.setup.mission_name]

            if hasattr(self.setup, "secondary_missions"):
                sec_mis = self.setup.secondary_missions
                if not isinstance(sec_mis, list):
                    sec_mis = [sec_mis]
            else:
                sec_mis = []

            self.missions = mis + sec_mis

            #
            # Obtain all observers.
            #
            obs = [f'{self.setup.observer}']

            if hasattr(self.setup, "secondary_observers"):
                sec_obs = self.setup.secondary_observers
                if not isinstance(sec_obs, list):
                    sec_obs = [sec_obs]
            else:
                sec_obs = []

            self.observers = obs + sec_obs

            #
            # Obtain all targets.
            #
            tar = [self.setup.target]

            if hasattr(self.setup, "secondary_targets"):
                sec_tar = self.setup.secondary_targets
                if not isinstance(sec_tar, list):
                    sec_tar = [sec_tar]
            else:
                sec_tar = []

            self.targets = tar + sec_tar
        else:
            self.missions = product.missions
            self.observers = product.observers
            self.targets = product.targets

    def write_label(self):
        """Write the Label."""
        label_dictionary = vars(self)

        if self._label_extension not in self.product.path:
            label_name = (
                self.product.path.split(f".{self.product.extension}")[0]
                + self._label_extension
            )
        else:
            #
            # This accounts for the bundle label, that doest not come
            # from the bundle product itself.
            #
            label_name = self.product.path

        if "inventory" in label_name:
            label_name = label_name.replace("inventory_", "")

        # Using newline guarantees that what we write into the file is what
        # we intend to write, independently of the platform.
        with open(label_name, "w+", encoding='utf-8', newline='') as f:
            with open(self.template, "r", encoding='utf-8') as t:
                for line in t:
                    line = line.rstrip()
                    for key, value in label_dictionary.items():
                        if isinstance(value, str) and key in line and "$" in line:
                            line = line.replace("$" + key, value)

                    #
                    # The checksum label for PDS3 in order to be equivalent to
                    # the one generated by mkpdssum.pl must have the same
                    # line length as the checksum file.
                    #
                    if label_name.split(os.sep)[-1] == "checksum.lbl":
                        line += " " * (self.product.record_bytes - len(line) - 2)
                    line = add_carriage_return(line, self._eol, self.setup)

                    f.write(line)

        self.name = label_name

        created_file = Path(label_name).relative_to(self.setup.staging_directory)

        logging.info('-- Created %s', created_file)

        if not self.setup.args.silent and not self.setup.args.verbose:
            print(f'   * Created {created_file}.')

        #
        # Add label to the list of generated files.
        #
        self.setup.add_file(str(created_file))

        #
        # Wrap lines for PDS3 labels.
        #
        if self.setup.diff:
            self.compare()

        if self.__class__.__name__ != "SpiceKernelPDS3Label":
            logging.info("")

    def compare(self):
        """**Compare the Label with another label**.

        The product label is compared to a similar label. The label with which
        the generated label is compared to is determined
        by the first criteria that is met from the following list:

           * find a different version of the same label
           * find the label of a product of the same kind (e.g.: same kernel
             type)
           * use a label of a product of the same kind from INSIGHT available
             from the NPB package.
        """
        logging.info("-- Comparing label...")

        #
        # 1-Look for a different version of the same file.
        #
        # What we do is that we keep trying to match the label name
        # advancing one character each iteration, in such a way that
        # we find, in order, the label that has the closest name to the
        # one we are generating.
        #
        val_label = ""
        try:

            match_flag = True
            val_label_path = (
                self.setup.bundle_directory
                + f"/{self.setup.mission_acronym}_spice/"
                + self.product.collection.name
                + os.sep
            )

            #
            # If this is the spice_kernels collection, we need to add the
            # kernel type directory. If it is the miscellaneous collection,
            # add the product type.
            #
            if (self.product.collection.name == "spice_kernels") and (
                "collection" not in self.name
            ):
                val_label_path += self.name.split(os.sep)[-2] + os.sep
            elif (self.product.collection.name == "miscellaneous") and (
                "collection" not in self.name
            ):
                val_label_path += self.name.split(os.sep)[-2] + os.sep

            val_label_name = self.name.split(os.sep)[-1]
            i = 1

            while match_flag and i < len(val_label_name) - 1:
                val_labels = glob.glob(
                    f"{val_label_path}{val_label_name[0:i]}*.xml"
                )
                if val_labels:
                    val_labels = sorted(val_labels)
                    val_label = val_labels[-1]
                    match_flag = True
                else:
                    match_flag = False
                i += 1

            if not val_label:
                raise Exception("No label for comparison found.")

        except BaseException:
            logging.warning("-- No other version of the product label has been found.")

            #
            # 2-If a prior version of the same file cannot be found look for
            #   the label of a product of the same type.
            #
            try:
                val_label_path = (
                    self.setup.bundle_directory
                    + f"/{self.setup.mission_acronym}_spice/"
                    + self.product.collection.name
                    + os.sep
                )

                #
                # If this is the spice_kernels collection, we need to add the
                # kernel type directory.
                #
                if (self.product.collection.name == "spice_kernels") and (
                    "collection" not in self.name
                ):
                    val_label_path += self.name.split(os.sep)[-2] + os.sep
                elif (self.product.collection.name == "miscellaneous") and (
                    "collection" not in self.name
                ):
                    val_label_path += self.name.split(os.sep)[-2] + os.sep

                product_extension = self.product.name.split(".")[-1]
                val_products = glob.glob(f"{val_label_path}*.{product_extension}")
                val_products.sort()

                #
                # Simply pick the last one
                #
                if "collection" in self.name.split(os.sep)[-1]:
                    val_label = glob.glob(
                        val_products[-1].replace("inventory_", "").split(".")[0]
                        + ".xml"
                    )[0]
                elif "bundle" in self.name.split(os.sep)[-1]:
                    val_labels = glob.glob(f"{val_label_path}bundle_*.xml")
                    val_labels.sort()
                    val_label = val_labels[-1]
                else:
                    val_label = glob.glob(val_products[-1].split(".")[0] + ".xml")[0]

                if not val_label:
                    raise Exception("No label for comparison found.")

            except BaseException:

                logging.warning("-- No similar label has been found.")
                #
                # 3-If we cannot find a kernel of the same type; for example
                #   is a first version of an archive, we compare with
                #   a label available in the test data directories.
                #
                try:
                    val_label_path = (
                        f"{self.setup.root_dir}"
                        f"/data/insight_spice/"
                        f"{self.product.collection.name}/"
                    )

                    #
                    # If this is the spice_kernels collection, we need to
                    # add the kernel type directory.
                    #
                    if (self.product.collection.name == "spice_kernels") and (
                        "collection" not in self.name
                    ):
                        val_label_path += self.name.split(os.sep)[-2] + os.sep
                    elif (self.product.collection.name == "miscellaneous") and (
                        "collection" not in self.name
                    ):
                        val_label_path += self.name.split(os.sep)[-2] + os.sep

                    #
                    # Simply pick the last one
                    #
                    product_extension = self.product.name.split(".")[-1]
                    val_products = glob.glob(f"{val_label_path}*.{product_extension}")
                    val_products.sort()

                    if "collection" in self.name.split(os.sep):
                        val_label = glob.glob(
                            val_products[-1].replace("inventory_", "").split(".")[0]
                            + ".xml"
                        )[0]
                    elif "bundle" in self.name.split(os.sep):
                        val_labels = glob.glob(f"{val_label_path}bundle_*.xml")
                        val_labels.sort()
                        val_label = val_labels[-1]
                    else:
                        val_label = glob.glob(val_products[-1].split(".")[0] + ".xml")[
                            0
                        ]

                    if not val_label:
                        raise Exception("No label for comparison found.")

                    logging.warning("-- Comparing with InSight test label.")
                except BaseException:
                    logging.warning("-- No label for comparison found.")

        #
        # If a similar label has been found the labels are compared and a
        # diff is being shown in the log. On top of that an HTML file with
        # the comparison is being generated.
        #
        if val_label:
            logging.info("")
            fromfile = val_label
            tofile = self.name
            work_dir = self.setup.working_directory

            compare_files(fromfile, tofile, work_dir, self.setup.diff)
