"""PDS Label Class and Child Classes Implementation."""

import glob
import logging
import os
from pathlib import Path
from typing import Optional

from ...utils import add_carriage_return, compare_files


class PDSLabel:
    """Class to generate a PDS Label.

    :param setup:   NPB execution Setup object
    :param product: Product to be labeled
    """

    _label_extension: str
    _eol: str
    _template: str

    def __init__(self, setup, product) -> None:
        """Constructor."""
        self.name = ''
        self.product = product
        self.setup = setup

        #
        # Fields from setup
        #
        self.root_dir = setup.root_dir
        self.mission_acronym = setup.mission_acronym

        if hasattr(self.setup, "creation_date_time"):
            creation_dt = self.setup.creation_date_time
            self.PRODUCT_CREATION_TIME = creation_dt
            self.PRODUCT_CREATION_DATE = creation_dt.split("T")[0]
            self.PRODUCT_CREATION_YEAR = creation_dt.split("-")[0]
        else:
            self.PRODUCT_CREATION_TIME = product.creation_time
            self.PRODUCT_CREATION_DATE = product.creation_date
            self.PRODUCT_CREATION_YEAR = product.creation_date.split("-")[0]

        self.FILE_SIZE = product.size
        self.FILE_CHECKSUM = product.checksum

        #
        # For labels that need to include all missions, observers and targets
        # of the setup.
        #
        if type(self).__name__ not in ('SpiceKernelPDS4Label', 'MetaKernelPDS4Label', 'OrbnumFilePDS4Label'):
            #
            # Obtain all Missions
            #
            mis = [self.setup.mission_name]

            if hasattr(self.setup, "secondary_missions"):
                sec_mis = self.setup.secondary_missions
                if not isinstance(sec_mis, list):
                    sec_mis = [sec_mis]
            else:
                sec_mis = []

            self.missions = mis + sec_mis

            #
            # Obtain all observers.
            #
            obs = [f'{self.setup.observer}']

            if hasattr(self.setup, "secondary_observers"):
                sec_obs = self.setup.secondary_observers
                if not isinstance(sec_obs, list):
                    sec_obs = [sec_obs]
            else:
                sec_obs = []

            self.observers = obs + sec_obs

            #
            # Obtain all targets.
            #
            tar = [self.setup.target]

            if hasattr(self.setup, "secondary_targets"):
                sec_tar = self.setup.secondary_targets
                if not isinstance(sec_tar, list):
                    sec_tar = [sec_tar]
            else:
                sec_tar = []

            self.targets = tar + sec_tar
        else:
            self.missions = product.missions
            self.observers = product.observers
            self.targets = product.targets

    def write_label(self):
        """Write the Label."""
        label_dictionary = vars(self)

        if self._label_extension not in self.product.path:
            label_name = (
                self.product.path.split(f".{self.product.extension}")[0]
                + self._label_extension
            )
        else:
            #
            # This accounts for the bundle label, that doest not come
            # from the bundle product itself.
            #
            label_name = self.product.path

        if "inventory" in label_name:
            label_name = label_name.replace("inventory_", "")

        # Using newline guarantees that what we write into the file is what
        # we intend to write, independently of the platform.
        with open(label_name, "w+", encoding='utf-8', newline='') as f:
            with open(self._template, "r", encoding='utf-8') as t:
                for line in t:
                    line = line.rstrip()
                    for key, value in label_dictionary.items():
                        if isinstance(value, str) and key in line and "$" in line:
                            line = line.replace("$" + key, value)

                    #
                    # The checksum label for PDS3 in order to be equivalent to
                    # the one generated by mkpdssum.pl must have the same
                    # line length as the checksum file.
                    #
                    if label_name.split(os.sep)[-1] == "checksum.lbl":
                        line += " " * (self.product.record_bytes - len(line) - 2)
                    line = add_carriage_return(line, self._eol, self.setup)

                    f.write(line)

        self.name = label_name

        created_file = Path(label_name).relative_to(self.setup.staging_directory)

        logging.info('-- Created %s', created_file)

        if not self.setup.args.silent and not self.setup.args.verbose:
            print(f'   * Created {created_file}.')

        #
        # Add label to the list of generated files.
        #
        self.setup.add_file(str(created_file))

        #
        # Wrap lines for PDS3 labels.
        #
        if self.setup.diff:
            self.compare()

        if self.__class__.__name__ != "SpiceKernelPDS3Label":
            logging.info("")

    def compare(self) -> None:
        """Compare the label with another label.

        The label to compare against is determined by the first criteria
        met from the following list, in order:

           * find a different version of the same label
           * find the label of a product of the same kind (e.g.: same kernel
             type)
           * use a label of a product of the same kind from INSIGHT available
             from the NPB package.
        """
        logging.info("-- Comparing label...")

        # Try each fallback level in turn and keep the first match found:
        # an older version of this label, then a label of the same type, then
        # the InSight stock example.
        val_label = (self._find_prior_version_label() or
                     self._find_similar_type_label() or
                     self._find_insight_fallback_label())

        if val_label:
            logging.info("")
            compare_files(val_label, self.name, self.setup.working_directory,
                          self.setup.diff)

    def _find_prior_version_label(self) -> Optional[str]:
        """Look for a different version of the same file (fallback level 1).

        Keeps trying to match the label name, advancing one character each
        iteration, so that we find, in order, the label with the closest
        name to the one being generated.

        :return: Path to the matching label, or ``None`` if none is found.
        """
        val_label = None
        match_flag = True
        val_label_path = self._val_label_directory(
            Path(self.setup.bundle_directory) / f"{self.setup.mission_acronym}_spice")

        val_label_name = Path(self.name).name
        i = 1

        while match_flag and i < len(val_label_name) - 1:

            val_labels = glob.glob(
                f"{val_label_path}{os.sep}{val_label_name[0:i]}*.xml")

            if val_labels:
                # Keep the newest match (highest version number) found so far,
                # in case a longer prefix finds nothing.
                val_label = max(val_labels)
                match_flag = True

            else:
                # A longer prefix only narrows the search, so if this length
                # finds nothing, no longer prefix will either.
                match_flag = False
            i += 1

        if not val_label:
            logging.warning("-- No other version of the product label has been found.")

        return val_label

    def _find_similar_type_label(self) -> Optional[Path]:
        """Look for the label of a product of the same type (fallback level 2).

        Used when a prior version of the same file cannot be found.

        :return: Path to the matching label, or ``None`` if none is found.
        """
        base_dir = Path(self.setup.bundle_directory) / f"{self.setup.mission_acronym}_spice"
        val_label = self._pick_val_label(base_dir)

        if not val_label:
            # No match at this level -- expected, not an error; the next
            # fallback level takes over.
            logging.warning("-- No similar label has been found.")

        return val_label

    def _find_insight_fallback_label(self) -> Optional[Path]:
        """Fall back to an InSight test label (fallback level 3).

        Used when no kernel of the same type can be found -- for example,
        the first version of an archive -- by comparing with a label
        available in the test data directories.

        :return: Path to the matching label, or ``None`` if none is found.
        """
        base_dir = Path(self.setup.root_dir) / "data" / "insight_spice"
        val_label = self._pick_val_label(base_dir)

        if val_label:
            logging.warning("-- Comparing with InSight test label.")
        else:
            # This is the last fallback level, so reaching here means no
            # label was found anywhere to compare against.
            logging.warning("-- No label for comparison found.")

        return val_label

    def _val_label_directory(self, base_dir: Path) -> Path:
        """Build the candidate-label directory for the product's collection.

        Appends the kernel-type/product-type subdirectory when the
        collection is spice_kernels or miscellaneous.

        :param base_dir: Root directory to build the candidate path under.
        :return: The candidate-label directory path.
        """
        val_label_path = Path(base_dir) / self.product.collection.name

        # spice_kernels and miscellaneous store their labels one level deeper,
        # in a subdirectory per kernel/product type (e.g. "ck", "orb"). A
        # collection label sits in the collection directory itself, not in one
        # of those subdirectories, so it's excluded from getting that extra
        # subdirectory appended.
        if (self.product.collection.name in ("spice_kernels", "miscellaneous")
                and ("collection" not in self.name)):

            val_label_path = val_label_path / Path(self.name).parent.name

        return val_label_path

    def _pick_val_label(self, base_dir: Path) -> Optional[Path]:
        """Select a validation label from a candidate directory.

        "collection"/"bundle" are matched as a substring of the label's
        basename (``Path(self.name).name``), not as a standalone path
        component. Real product names embed them as a prefix -- e.g.
        "collection_spice_kernels_v001.xml", "bundle_insight_spice_v009.xml"
        -- never as a bare directory/path segment, so an exact-component
        check would never match real files.

        :param base_dir: Root directory to search under.
        :return: Path to the selected validation label, or ``None`` if none
            is found.
        """
        val_label_path = self._val_label_directory(base_dir)
        basename = Path(self.name).name

        # Bundle labels are matched directly by their own glob pattern;
        # everything else is derived from the newest matching product file.
        if "bundle" in basename:
            pattern = "bundle_*.xml"
        else:
            pattern = f"*{Path(self.product.name).suffix}"

        matches = list(val_label_path.glob(pattern))
        if not matches:

            # Nothing in this directory to compare against.
            return None

        # File names carry a version number, so the alphabetically greatest
        # path is also the newest version.
        matched = max(matches)

        if "bundle" in basename:
            return matched

        if "collection" in basename:
            # Collection products are named "inventory_*"; the label itself
            # drops that prefix, so it must be stripped to derive its name.
            matched = matched.with_name(matched.name.replace("inventory_", ""))

        candidate = matched.with_suffix(".xml")

        # The stem match doesn't guarantee a label was actually generated for
        # that product (e.g. it may have been skipped or failed).
        if not candidate.exists():
            return None

        return candidate
